# Generated by Django 5.2.8 on 2025-11-29 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('academic', 'Academic Support'), ('mental_health', 'Mental Health & Wellbeing'), ('career', 'Career Guidance'), ('other', 'Other Resources')], default='academic', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='support_resources/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(default='file-alt', help_text='FontAwesome icon name (e.g., file-pdf)', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_date', models.DateField(help_text='Preferred date for the appointment')),
                ('preferred_time', models.TimeField(blank=True, help_text='Preferred time', null=True)),
                ('reason', models.TextField(help_text="Briefly describe why you'd like to meet")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for counselors')),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_support.counselor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
