# Generated by Django 5.1.4 on 2024-12-21 17:37

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=255)),
                ('short_description', tinymce.models.HTMLField(help_text='This will be shown on the home page.')),
                ('long_description', tinymce.models.HTMLField(help_text='This will be shown on the detailed page.')),
                ('main_image', models.ImageField(default='path/to/default/main_image.jpg', help_text='Main image for the home page.', upload_to='about_us/')),
                ('additional_images', models.ImageField(blank=True, help_text='Additional images for the detailed page.', null=True, upload_to='about_us/')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='faculty_images/')),
                ('category', models.CharField(choices=[('Administration', 'Administration'), ('Teacher', 'Teacher'), ('Office Staff', 'Office Staff')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('content', models.FileField(blank=True, null=True, upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the message', max_length=200)),
                ('message', models.TextField(help_text='The main message')),
                ('image', models.ImageField(blank=True, help_text='Optional: Upload an image', null=True, upload_to='principal_images/')),
                ('is_active', models.BooleanField(default=True, help_text='Mark as active to display')),
                ('type', models.CharField(choices=[('Principal', "Principal's Message"), ('VicePrincipal', "Vice-Principal's Message")], default='Principal', help_text='Select the type of message', max_length=20)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='home.aboutus')),
            ],
        ),
    ]
