# Generated by Django 5.2.7 on 2025-11-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Slider Image', 'verbose_name_plural': 'Slider Images'},
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='action_url',
            field=models.URLField(blank=True, help_text="Optional URL for 'Learn More' button"),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description shown on the slide'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this slide'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of appearance (lower numbers appear first)'),
        ),
    ]
