# Generated by Django 5.1.4 on 2026-05-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name for the popup (e.g. Admission Open 2026)', max_length=255)),
                ('image', models.ImageField(help_text='The main advertisement image. Vertical/Square images work best.', upload_to='popups/')),
                ('link', models.URLField(blank=True, help_text='Optional: URL to redirect when the image is clicked.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Check to display this popup on the website.')),
                ('show_once_per_session', models.BooleanField(default=True, help_text='If checked, the popup will only appear once per browser session.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Popup Announcement',
                'verbose_name_plural': 'Popup Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo_footer',
            field=models.ImageField(blank=True, help_text='Optional: Light/White logo for dark footers', null=True, upload_to='site_config/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address shown in footer'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(help_text='Primary logo (shown on light backgrounds)', upload_to='site_config/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number', max_length=50),
        ),
    ]
