# Generated by Django 5.1.4 on 2026-05-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_popupannouncement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupannouncement',
            name='image',
            field=models.ImageField(help_text='Best size: 800px x 1000px (Vertical) or 800px x 800px (Square). High-resolution PNG or JPG recommended.', upload_to='popups/'),
        ),
    ]
