# Generated by Django 5.1.4 on 2026-05-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_popupannouncement_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Slider Item', 'verbose_name_plural': 'Slider Items'},
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video File'), ('youtube', 'YouTube Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a direct video file (MP4 recommended)', null=True, upload_to='carousel_videos/'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Enter YouTube video URL (e.g., https://www.youtube.com/watch?v=...)'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(help_text='Used for image slides or as a placeholder/poster for videos', upload_to='carousel_images/'),
        ),
    ]
