# Generated by Django 5.1.4 on 2026-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_carouselimage_options_carouselimage_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupannouncement',
            name='desktop_image',
            field=models.ImageField(blank=True, help_text='Desktop Image: Best size 1200px x 600px (Wide). Shown on Laptops/Desktops. If empty, mobile image will be used.', null=True, upload_to='popups/'),
        ),
        migrations.AlterField(
            model_name='popupannouncement',
            name='image',
            field=models.ImageField(help_text='Mobile Image: Best size 800px x 1000px (Vertical). Shown on phones.', upload_to='popups/'),
        ),
    ]
