# Generated by Django 5.1.4 on 2026-08-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_popupannouncement_desktop_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultymember',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='facultymember',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers like 1, 2, 3 appear first). Set 1 for Principal.'),
        ),
    ]
