# Generated by Django 5.1.4 on 2026-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_facultymember_options_facultymember_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalmessage',
            name='email',
            field=models.EmailField(blank=True, help_text='Direct or official contact email (e.g., principal@sjis.edu.bd)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='principalmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional direct office phone number', max_length=50, null=True),
        ),
    ]
