# Generated by Django 5.2.8 on 2025-11-29 05:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearbookEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Academic year (e.g., 2024 for 2024-2025)', unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('title', models.CharField(help_text="e.g., 'Memories 2024-2025'", max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='yearbook/covers/')),
                ('description', models.TextField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Make this yearbook visible to the public')),
                ('pdf_file', models.FileField(blank=True, help_text='Full yearbook PDF', null=True, upload_to='yearbook/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yearbook Edition',
                'verbose_name_plural': 'Yearbook Editions',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='YearbookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Name of the person', max_length=200)),
                ('position', models.CharField(help_text="e.g., 'Principal', 'Vice Principal'", max_length=200)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='yearbook/messages/')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('yearbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='yearbook.yearbookedition')),
            ],
            options={
                'verbose_name': 'Yearbook Message',
                'verbose_name_plural': 'Yearbook Messages',
                'ordering': ['order', 'author'],
            },
        ),
        migrations.CreateModel(
            name='YearbookQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=100)),
                ('quote', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='yearbook/quotes/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on main yearbook page')),
                ('yearbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='yearbook.yearbookedition')),
            ],
            options={
                'verbose_name': 'Student Quote',
                'verbose_name_plural': 'Student Quotes',
            },
        ),
        migrations.CreateModel(
            name='YearbookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Material icon name', max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('yearbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='yearbook.yearbookedition')),
            ],
            options={
                'verbose_name': 'Yearbook Section',
                'verbose_name_plural': 'Yearbook Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='YearbookPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yearbook/photos/')),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_class', models.CharField(blank=True, help_text="e.g., 'Grade 10A'", max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within section')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='yearbook.yearbooksection')),
            ],
            options={
                'verbose_name': 'Yearbook Photo',
                'verbose_name_plural': 'Yearbook Photos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
