# Generated by Django 5.1.4 on 2026-05-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearbookphoto',
            name='section',
        ),
        migrations.RemoveField(
            model_name='yearbookquote',
            name='yearbook',
        ),
        migrations.RemoveField(
            model_name='yearbooksection',
            name='yearbook',
        ),
        migrations.DeleteModel(
            name='YearbookMessage',
        ),
        migrations.DeleteModel(
            name='YearbookPhoto',
        ),
        migrations.DeleteModel(
            name='YearbookQuote',
        ),
        migrations.DeleteModel(
            name='YearbookSection',
        ),
    ]
